### ISSUE TITLE
富文本TinyMCE无法正常插入多媒体资源

### ISSUE THREAD

**Issue by lp110lp** [jqhph/dcat-admin#248]
- Laravel Version: 7.0
- PHP Version: 7.3.4
- Dcat Admin Version: #.#.#

### Description:
插入视频代码片段无法入库，视频地址无法正常显示预览

**Comment by jqhph** [comment]
已修复，你可以先更新master分支代码

**Comment by jqhph** [comment]
新版本已发布，更新到1.5.3版本即可

**Comment by liujingencris** [comment]
没有解决啊  我已经更新到1.6版本了 依然无法预览

**Comment by jqhph** [comment]
> 没有解决啊 我已经更新到1.6版本了 依然无法预览

录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的

**Comment by liujingencris** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 下午5:16
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
没有解决啊 我已经更新到1.6版本了 依然无法预览
  
录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的

**Comment by liujingencris** [comment]
这是动图


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 下午5:16
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
没有解决啊 我已经更新到1.6版本了 依然无法预览
  
录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的

**Comment by jqhph** [comment]
> 这是动图
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

看不到

**Comment by liujingencris** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午3:17
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
这是动图
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看不到

**Comment by liujingencris** [comment]
在邮件当中看




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午3:17
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
这是动图
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
看不到

**Comment by jqhph** [comment]
> 在邮件当中看
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

邮件当中也没有图片

**Comment by liujingencris** [comment]
有的&nbsp; 你在试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午3:21
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
在邮件当中看
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
邮件当中也没有图片

**Comment by liujingencris** [comment]
怎么做到在表单里面点击按钮下载一个本地的文件啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午3:21
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
在邮件当中看
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
邮件当中也没有图片

**Comment by jqhph** [comment]
> 怎么做到在表单里面点击按钮下载一个本地的文件啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 在邮件当中看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件当中也没有图片 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

```php
$form->html('<a>下载按钮</a>');
```

**Comment by liujingencris** [comment]
搞错了 不是表单 是在列表页下载



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午5:17
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
怎么做到在表单里面点击按钮下载一个本地的文件啊
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 在邮件当中看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件当中也没有图片 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  $form-&gt;html('<a&gt;下载按钮</a&gt;');

**Comment by jqhph** [comment]
> 搞错了 不是表单 是在列表页下载
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午5:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 怎么做到在表单里面点击按钮下载一个本地的文件啊 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 在邮件当中看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件当中也没有图片 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. $form-&gt;html('<a&gt;下载按钮</a&gt;'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

方法太多了，看文档吧

**Comment by liujingencris** [comment]
你随便说一个&nbsp; 文档我没找到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年7月21日(星期二) 下午5:21
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248)





  
搞错了 不是表单 是在列表页下载
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午5:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 怎么做到在表单里面点击按钮下载一个本地的文件啊 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 在邮件当中看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件当中也没有图片 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. $form-&gt;html('<a&gt;下载按钮</a&gt;'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
方法太多了，看文档吧

**Comment by jqhph** [comment]
> 你随便说一个&nbsp; 文档我没找到
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午5:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 搞错了 不是表单 是在列表页下载 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午5:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 怎么做到在表单里面点击按钮下载一个本地的文件啊 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:21 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 在邮件当中看 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jiang Qinghua"<notifications@github.com&gt;; 发送时间: 2020年7月21日(星期二) 下午3:17 收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送: "ECHI"<840474265@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 主题: Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 这是动图 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "jqhph/dcat-admin" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月20日(星期一) 下午5:16 收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;"ECHI"<840474265@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [jqhph/dcat-admin] 富文本TinyMCE无法正常插入多媒体资源 (#248) 没有解决啊 我已经更新到1.6版本了 依然无法预览 录制视频或者动态图看看你的操作，插入媒体资源的问题是解决了的 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 看不到 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 邮件当中也没有图片 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. $form-&gt;html('<a&gt;下载按钮</a&gt;'); — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 方法太多了，看文档吧 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

工具栏就去看工具栏的文档，行操作就看行操作的文档，字段显示就看字段显示，你场景都不说清楚我怎么知道你想怎么加？
