### ISSUE TITLE
English docs version?

### ISSUE THREAD

**Issue by fhferreira** [jqhph/dcat-admin#52]
Do you have english version of docs? http://www.dcatadmin.com/docs/master/introduction.html

**Comment by jqhph** [comment]
Not yet, maybe you can use google's translation service

**Comment by fhferreira** [comment]
Great, I will try that, the bad notice is that Google Translate, cause some troubles through the <code></code>

**Comment by shacky** [comment]
Bump it up! I thinking about moving my app from laravel-admin to dcat-admin, because laravel-admin development is very slow and ages before dcat-admin. @jqhph - you are doing a great job, but it would be nice to have programmers all over the world. Without English docs and English support (issues) it's not possible. The main project programmers language should be English :)

**Comment by jqhph** [comment]
@shacky @fhferreira  English docs http://www.dcatadmin.com/docs/en-2.x/quick-start.html

**Comment by shacky** [comment]
@jqhph Wow! Great - it will be easier to find something :) Thank you!
